apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  labels:
    app: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
       app: jenkins
  template:
    metadata:
      name: web-deploy
      labels:
        app: jenkins
    spec:
      volumes:
        - name: web-pv
          persistentVolumeClaim:
            claimName: web-pvc
      containers:
        - name: jenkins
          image: chatpc99/webos:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: "/task4"
              name: web-pv
      restartPolicy: Always

 


       