apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: web-pvc
 labels: 
   name: web-pvc
spec:  
  storageClassName: manual
  accessModes: 
   - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi